-- MySQL Script generated by MySQL Workbench
-- Tue Dec 11 21:56:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olx` DEFAULT CHARACTER SET utf8 ;
USE `olx` ;

-- -----------------------------------------------------
-- Table `olx`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `gender` TINYINT NULL,
  `address` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `cart` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`ads` (
  `idads` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  `description` TEXT NULL,
  `location` VARCHAR(45) NULL,
  `categorie` VARCHAR(45) NULL,
  `image` TEXT NULL,
  `seller` VARCHAR(45) NULL,
  PRIMARY KEY (`idads`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`adminusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`adminusers` (
  `idadminusers` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idadminusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
