-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 13:32:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olx` DEFAULT CHARACTER SET utf8 ;
USE `olx` ;

-- -----------------------------------------------------
-- Table `olx`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `gender` TINYINT NULL,
  `address` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`ads` (
  `idads` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `categorie` VARCHAR(45) NULL,
  `image` TEXT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idads`),
  INDEX `fk_ads_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_ads_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `olx`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`adminusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`adminusers` (
  `idadminusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idadminusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
